default: &defaults

  summary_metrics:
    - impressions
    - ga:sessions
    - clicks
    - ctr
    - cpc
    - ga:goalCompletionsAll
    - ga:costPerGoalConversion
    - ga:avgSessionDuration

  client_channel_subclasses:
    - ClientChannels::Facebook
    - ClientChannels::Twitter

  csv_header_columns:
    date_start: 'Date'
    account_name: 'Account Name'
    campaign_name: 'Campaign Name'
    spend: 'Spend'
    impressions: 'Impressions'
    clicks: 'Clicks'
    cpm: 'CPM'
    reach: 'Reach'
    cpp: 'CPP'
    ctr: 'CTR'
    cpc: 'CPC'

  summary_header_columns:
    impressions: 'Impressions'
    clicks: 'Clicks'
    cpc: 'CPC'
    ctr: 'CTR'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults