default: &defaults

  client_channel_subclasses:
    - ClientChannels::Adwords
    - ClientChannels::Facebook
    - ClientChannels::Instagram
    - ClientChannels::Twitter

  csv_header_columns:
    date_start: 'Date'
    account_name: 'Account Name'
    campaign_name: 'Campaign Name'
    spend: 'Spend'
    impressions: 'Impressions'
    clicks: 'Clicks'
    cpm: 'CPM'
    reach: 'Reach'
    cpp: 'CPP'
    ctr: 'CTR'
    cpc: 'CPC'
    'ga:sessions': 'Sessions'
    'ga:avgSessionDuration': 'Avg Session Duration'
    'ga:goalCompletionsAll': 'Goal Completions (all)'
    'ga:costPerGoalConversion': 'Cost per Goal Conversion'

  summary_header_columns:
    impressions: 'Impressions'
    clicks: 'Clicks'
    spend: 'Spend'
    cpc: 'CPC'
    ctr: 'CTR'
    'ga:sessions': 'Sessions'
    'ga:avgSessionDuration': 'Avg Session Duration'
    'ga:goalCompletionsAll': 'Goal Completions (all)'
    'ga:costPerGoalConversion': 'Cost per Goal Conversion'

  adwords:
    oauth2_client_id: <%= ENV["ADWORDS_OAUTH2_CLIENT_ID"] %>
    oauth2_client_secret: <%= ENV["ADWORDS_OAUTH2_CLIENT_SECRET"] %>
    developer_token: <%= ENV["ADWORDS_DEVELOPER_TOKEN"] %>
    oauth2_token: 
      access_token: <%= ENV["ADWORDS_ACCESS_TOKEN"] %>
      refresh_token: <%= ENV["ADWORDS_REFRESH_TOKEN"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
