default: &defaults

  summary_metrics:
    - impressions
    - ga:sessions
    - clicks
    - ctr
    - cpc
    - ga:goalCompletionsAll
    - ga:costPerGoalConversion
    - ga:avgSessionDuration

  exclude_metrics:
    - cpp
    - reach

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults