default: &defaults

  summary_metrics:
    - impressions
    - ga:sessions
    - clicks
    - ctr
    - cpc
    - ga:goalCompletionsAll
    - ga:costPerGoalConversion
    - ga:avgSessionDuration

  client_channel_subclasses:
    - ClientChannels::Facebook
    - ClientChannels::Twitter

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults