default: &defaults

  client_channel_subclasses:
    - ClientChannels::Adwords
    - ClientChannels::Facebook
    - ClientChannels::Instagram
    - ClientChannels::Twitter

  adwords_headers:
    for_csv:
      CampaignName: 'Campaign'
      Impressions: 'Impressions'
      Clicks: 'Clicks'
      Cost: 'Cost'
    for_summary:
      CampaignName: 'Campaign'
      Impressions: 'Impressions'
      Clicks: 'Clicks'
      Cost: 'Cost'
  facebook_headers:
    for_csv:
      date_start: 'Date'
      account_name: 'Account Name'
      campaign_name: 'Campaign Name'
      spend: 'Spend'
      impressions: 'Impressions'
      clicks: 'Clicks'
      cpm: 'CPM'
      reach: 'Reach'
      cpp: 'CPP'
      ctr: 'CTR'
      cpc: 'CPC'
    for_summary:
      impressions: 'Impressions'
      clicks: 'Clicks'
      spend: 'Spend'
      cpc: 'CPC'
      ctr: 'CTR'
  google_analytics_headers:
    for_csv:
      'ga:sessions': 'Sessions'
      'ga:avgSessionDuration': 'Avg Session Duration'
      'ga:goalCompletionsAll': 'Goal Completions (all)'
      'ga:costPerGoalConversion': 'Cost per Goal Conversion'
    for_summary:
      'ga:sessions': 'Sessions'
      'ga:avgSessionDuration': 'Avg Session Duration'
      'ga:goalCompletionsAll': 'Goal Completions (all)'
      'ga:costPerGoalConversion': 'Cost per Goal Conversion'

  adwords:
    oauth2_client_id: <%= ENV["ADWORDS_OAUTH2_CLIENT_ID"] %>
    oauth2_client_secret: <%= ENV["ADWORDS_OAUTH2_CLIENT_SECRET"] %>
    developer_token: <%= ENV["ADWORDS_DEVELOPER_TOKEN"] %>
    user_agent: 'eight&four'
    oauth2_token: 
      refresh_token: <%= ENV["ADWORDS_REFRESH_TOKEN"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
