default: &defaults

  client_channel_subclasses:
    - ClientChannels::Adwords
    - ClientChannels::Facebook
    - ClientChannels::Instagram
    - ClientChannels::Twitter

  adwords_headers:
    for_csv:
      AccountDescriptiveName: 'Account Name'
      Date: 'Date'
      CampaignName: 'Campaign'
      Labels: 'Labels'
      Impressions: 'Impressions'
      Clicks: 'Clicks'
      Ctr: 'Ctr'
      AverageCpc: 'Average CPC'
      Cost: 'Cost'
      AveragePosition: 'Average Position'
      Conversions: 'Conversions'
      ConversionRate: 'Conversion Rate'
      SearchImpressionShare: 'Search Impression Share'
      NumOfflineInteractions: 'Calls'
      AverageTimeOnSite: 'Avg Time on Site'
      BounceRate: 'Bounce Rate'
      AveragePageviews: 'Avg Pageviews'
      PercentNewVisitors: 'PercentNewVisitors'
  facebook_headers:
    for_csv:
      date_start: 'Date'
      account_name: 'Account Name'
      campaign_name: 'Campaign Name'
      spend: 'Spend'
      impressions: 'Impressions'
      clicks: 'Clicks'
      cpm: 'CPM'
      reach: 'Reach'
      cpp: 'CPP'
      ctr: 'CTR'
      cpc: 'CPC'
    for_summary:
      impressions: 'Impressions'
      clicks: 'Clicks'
      spend: 'Spend'
      cpc: 'CPC'
      ctr: 'CTR'
  google_analytics_headers:
    for_csv:
      'ga:sessions': 'Sessions'
      'ga:avgSessionDuration': 'Avg Session Duration'
      'ga:goalCompletionsAll': 'Goal Completions (all)'
      # 'ga:goal1Completions': 'Goal 1 Competions'
      # 'ga:goal2Completions': 'Goal 2 Competions'
      # 'ga:goal3Completions': 'Goal 3 Competions'
      # 'ga:goal4Completions': 'Goal 4 Competions'
      # 'ga:goal5Completions': 'Goal 5 Competions'
      # 'ga:goal6Completions': 'Goal 6 Competions'
      # 'ga:goal7Completions': 'Goal 7 Competions'
      # 'ga:goal8Completions': 'Goal 8 Competions'
      # 'ga:goal9Completions': 'Goal 9 Competions'
      # 'ga:goal10Completions': 'Goal 10 Competions'
      # 'ga:goal11Completions': 'Goal 11 Competions'
      # 'ga:goal12Completions': 'Goal 12 Competions'
      # 'ga:goal13Completions': 'Goal 13 Competions'
      # 'ga:goal14Completions': 'Goal 14 Competions'
      # 'ga:goal15Completions': 'Goal 15 Competions'
      # 'ga:goal16Completions': 'Goal 16 Competions'
      # 'ga:goal17Completions': 'Goal 17 Competions'
      # 'ga:goal18Completions': 'Goal 18 Competions'
      # 'ga:goal19Completions': 'Goal 19 Competions'
      # 'ga:goal20Completions': 'Goal 20 Competions'
      # 'ga:costPerGoalConversion': 'Cost per Goal Conversion'

  adwords:
    oauth2_client_id: <%= ENV["ADWORDS_OAUTH2_CLIENT_ID"] %>
    oauth2_client_secret: <%= ENV["ADWORDS_OAUTH2_CLIENT_SECRET"] %>
    developer_token: <%= ENV["ADWORDS_DEVELOPER_TOKEN"] %>
    user_agent: 'eight&four'
    oauth2_token: 
      refresh_token: <%= ENV["ADWORDS_REFRESH_TOKEN"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
